name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  # ─── Lint & Type-check ──────────────────────────────────────────────────────
  lint:
    name: Lint & Type-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install root dependencies
        run: npm ci

      - name: Install SDK dependencies
        working-directory: packages/sdk
        run: npm ci

      - name: Type-check SDK
        working-directory: packages/sdk
        run: npx tsc --noEmit

      - name: Lint SDK
        working-directory: packages/sdk
        run: npm run lint

  # ─── SDK Drift Detection ────────────────────────────────────────────────────
  sdk-drift:
    name: SDK Drift Detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Set up Java (required by openapi-generator)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install SDK dependencies
        working-directory: packages/sdk
        run: npm ci

      - name: Regenerate SDK from OpenAPI spec
        working-directory: packages/sdk
        run: npm run generate

      - name: Check for uncommitted changes (drift detection)
        run: |
          git diff --exit-code packages/sdk/src/generated/ || {
            echo ""
            echo "❌ SDK drift detected!"
            echo ""
            echo "The generated SDK (packages/sdk/src/generated/) is out of sync"
            echo "with docs/openapi.json."
            echo ""
            echo "To fix this, run the following locally and commit the result:"
            echo ""
            echo "  cd packages/sdk && npm run generate"
            echo "  git add packages/sdk/src/generated"
            echo "  git commit -m 'chore(sdk): regenerate from updated OpenAPI spec'"
            echo ""
            git diff packages/sdk/src/generated/
            exit 1
          }
          echo "✅ SDK is in sync with the OpenAPI spec."

  # ─── Build ──────────────────────────────────────────────────────────────────
  build:
    name: Build SDK
    runs-on: ubuntu-latest
    needs: [lint, sdk-drift]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install SDK dependencies
        working-directory: packages/sdk
        run: npm ci

      - name: Build SDK
        working-directory: packages/sdk
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sdk-dist
          path: packages/sdk/dist/
          retention-days: 7

  # ─── Tests ──────────────────────────────────────────────────────────────────
  test:
    name: Test SDK
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install SDK dependencies
        working-directory: packages/sdk
        run: npm ci

      - name: Run tests
        working-directory: packages/sdk
        run: npm test -- --coverage

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: packages/sdk/coverage/
