name: Release

on:
  push:
    tags:
      - 'v*.*.*'   # Triggers on semver tags: v1.0.0, v1.2.3-beta.1, etc.

permissions:
  contents: write   # needed to create GitHub releases
  id-token: write   # needed for npm provenance

jobs:
  # ─── Validate tag matches package.json version ──────────────────────────────
  validate-version:
    name: Validate Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Extract version from tag
        id: extract
        run: |
          TAG="${GITHUB_REF#refs/tags/v}"
          echo "version=$TAG" >> "$GITHUB_OUTPUT"
          echo "Tag version: $TAG"

      - name: Verify package.json version matches tag
        run: |
          PKG_VERSION=$(node -p "require('./packages/sdk/package.json').version")
          TAG_VERSION="${{ steps.extract.outputs.version }}"
          if [ "$PKG_VERSION" != "$TAG_VERSION" ]; then
            echo "❌ Version mismatch: tag is v$TAG_VERSION but package.json is $PKG_VERSION"
            echo "Update packages/sdk/package.json version before tagging."
            exit 1
          fi
          echo "✅ Version matches: $PKG_VERSION"

  # ─── Run full CI suite ───────────────────────────────────────────────────────
  ci:
    name: Run CI checks
    needs: validate-version
    uses: ./.github/workflows/ci.yml

  # ─── Publish to npm ──────────────────────────────────────────────────────────
  publish:
    name: Publish @medchain/sdk to npm
    runs-on: ubuntu-latest
    needs: [validate-version, ci]
    environment: npm-publish  # requires NPM_TOKEN secret in this GitHub environment
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js with npm registry
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install SDK dependencies
        working-directory: packages/sdk
        run: npm ci

      - name: Build SDK
        working-directory: packages/sdk
        run: npm run build

      - name: Publish to npm
        working-directory: packages/sdk
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  # ─── Create GitHub Release ───────────────────────────────────────────────────
  github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [validate-version, publish]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # full history for changelog generation

      - name: Generate changelog since last tag
        id: changelog
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -n "$PREV_TAG" ]; then
            LOG=$(git log "$PREV_TAG"..HEAD --pretty=format:"- %s (%h)" --no-merges)
          else
            LOG=$(git log --pretty=format:"- %s (%h)" --no-merges)
          fi
          echo "changelog<<EOF" >> "$GITHUB_OUTPUT"
          echo "$LOG" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ needs.validate-version.outputs.version }}
          body: |
            ## @medchain/sdk v${{ needs.validate-version.outputs.version }}

            Install via npm:
            ```bash
            npm install @medchain/sdk@${{ needs.validate-version.outputs.version }}
            ```

            ### Changes
            ${{ steps.changelog.outputs.changelog }}

            ### Links
            - [npm package](https://www.npmjs.com/package/@medchain/sdk/v/${{ needs.validate-version.outputs.version }})
            - [OpenAPI Spec](https://github.com/medchain/medchain/blob/v${{ needs.validate-version.outputs.version }}/docs/openapi.json)
