export enum MedicalRole {
  DOCTOR = 'DOCTOR',
  NURSE = 'NURSE',
  PHARMACIST = 'PHARMACIST',
  LAB_TECHNICIAN = 'LAB_TECHNICIAN',
  ADMIN = 'ADMIN',
}

export enum MedicalDepartment {
  CARDIOLOGY = 'CARDIOLOGY',
  SURGERY = 'SURGERY',
  EMERGENCY = 'EMERGENCY',
  PEDIATRICS = 'PEDIATRICS',
  ONCOLOGY = 'ONCOLOGY',
  NEUROLOGY = 'NEUROLOGY',
  RADIOLOGY = 'RADIOLOGY',
  PHARMACY = 'PHARMACY',
  LABORATORY = 'LABORATORY',
  GENERAL = 'GENERAL',
}

export enum MedicalSpecialty {
  CARDIOLOGIST = 'CARDIOLOGIST',
  SURGEON = 'SURGEON',
  PEDIATRICIAN = 'PEDIATRICIAN',
  ONCOLOGIST = 'ONCOLOGIST',
  NEUROLOGIST = 'NEUROLOGIST',
  RADIOLOGIST = 'RADIOLOGIST',
  GENERAL_PRACTITIONER = 'GENERAL_PRACTITIONER',
}

export enum MedicalPermission {
  // Patient data
  READ_PATIENT_BASIC = 'READ_PATIENT_BASIC',
  READ_PATIENT_FULL = 'READ_PATIENT_FULL',
  WRITE_PATIENT_DATA = 'WRITE_PATIENT_DATA',
  DELETE_PATIENT_DATA = 'DELETE_PATIENT_DATA',

  // Medical records
  READ_MEDICAL_RECORDS = 'READ_MEDICAL_RECORDS',
  WRITE_MEDICAL_RECORDS = 'WRITE_MEDICAL_RECORDS',
  READ_LAB_RESULTS = 'READ_LAB_RESULTS',
  WRITE_LAB_RESULTS = 'WRITE_LAB_RESULTS',

  // Prescriptions
  READ_PRESCRIPTIONS = 'READ_PRESCRIPTIONS',
  WRITE_PRESCRIPTIONS = 'WRITE_PRESCRIPTIONS',
  DISPENSE_MEDICATIONS = 'DISPENSE_MEDICATIONS',

  // Department specific
  ACCESS_OWN_DEPARTMENT = 'ACCESS_OWN_DEPARTMENT',
  ACCESS_ANY_DEPARTMENT = 'ACCESS_ANY_DEPARTMENT',

  // Emergency
  EMERGENCY_OVERRIDE = 'EMERGENCY_OVERRIDE',

  // Administrative
  MANAGE_STAFF = 'MANAGE_STAFF',
  VIEW_AUDIT_LOGS = 'VIEW_AUDIT_LOGS',
  MANAGE_SYSTEM = 'MANAGE_SYSTEM',
}

export enum AuditAction {
  READ = 'READ',
  WRITE = 'WRITE',
  DELETE = 'DELETE',
  EMERGENCY_OVERRIDE = 'EMERGENCY_OVERRIDE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
}
